 2022-05-02 15:10:04,410 - 'd'
 2022-05-02 15:10:04,521 - 'a'
 2022-05-02 15:10:04,537 - 's'
 2022-05-02 15:10:04,601 - 'd'
 2022-05-02 15:10:04,650 - 'a'
 2022-05-02 15:10:04,762 - 's'
 2022-05-02 15:10:04,770 - 'a'
 2022-05-02 15:10:04,842 - 'd'
 2022-05-02 15:10:04,890 - 'a'
 2022-05-02 15:10:04,898 - 's'
 2022-05-02 15:10:04,961 - 'd'
 2022-05-02 15:10:05,017 - 'a'
 2022-05-02 15:10:05,025 - 's'
 2022-05-02 15:10:05,089 - 'd'
 2022-05-02 15:10:05,145 - 'a'
 2022-05-02 15:10:05,153 - 's'
 2022-05-02 15:10:05,161 - 'd'
 2022-05-02 15:10:05,265 - 'a'
 2022-05-02 15:10:05,273 - 's'
 2022-05-02 15:10:05,338 - 'd'
 2022-05-02 15:10:05,385 - 's'
 2022-05-02 15:10:05,393 - 'a'
 2022-05-02 15:10:05,506 - 'a'
 2022-05-02 15:10:05,514 - 's'
 2022-05-02 15:10:05,585 - 'd'
 2022-05-02 15:10:05,633 - 'a'
 2022-05-02 15:10:05,641 - 's'
 2022-05-02 15:10:05,721 - 'd'
 2022-05-02 15:10:05,761 - 's'
 2022-05-02 15:10:05,873 - 'a'
 2022-05-02 15:10:05,881 - 's'
 2022-05-02 15:10:06,002 - 'a'
 2022-05-02 15:10:06,009 - 's'
 2022-05-02 15:10:06,137 - 'a'
 2022-05-02 15:10:06,145 - 's'
 2022-05-02 15:10:06,273 - 'a'
 2022-05-02 15:10:06,281 - 's'
 2022-05-02 15:10:06,401 - 'a'
 2022-05-02 15:10:06,409 - 's'
 2022-05-02 15:10:06,529 - 's'
 2022-05-02 15:10:06,537 - 'd'
 2022-05-02 15:10:06,545 - 'a'
 2022-05-02 15:10:06,657 - 'a'
 2022-05-02 15:10:06,665 - 's'
 2022-05-02 15:10:06,729 - 'd'
 2022-05-02 15:10:06,762 - 'a'
 2022-05-02 15:10:06,769 - 's'
 2022-05-02 15:10:06,857 - 'd'
 2022-05-02 15:10:06,897 - 'a'
 2022-05-02 15:10:06,905 - 's'
 2022-05-02 15:10:07,033 - 'a'
 2022-05-02 15:10:07,034 - Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pynput\_util\__init__.py", line 228, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pynput\keyboard\_win32.py", line 287, in _process
    self.on_press(key)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pynput\_util\__init__.py", line 144, in inner
    if f(*args) is False:
  File "c:\Users\User\Documents\School\Anti-Keylogger\Keylogger\keylogger.py", line 28, in on_press
    Keylogger.email(keys)
NameError: name 'Keylogger' is not defined
